// leave off @2x/@3x
const images = {
  // sponsors
  amazonSponsor: require('../Images/sponsors/img-sponsor-amazon web services.png'),
  capitalOneSponsor: require('../Images/sponsors/img-sponsor-capital-one.png'),
  echobindSponsor: require('../Images/sponsors/img-sponsor-echobind.png'),
  formidableSponsor: require('../Images/sponsors/img-sponsor-formidable.png'),
  gudogSponsor: require('../Images/sponsors/img-sponsor-gudog.png'),
  instrumentSponsor: require('../Images/sponsors/img-sponsor-instrument.png'),
  modusSponsor: require('../Images/sponsors/img-sponsor-modus-create.png'),
  nativeBaseSponsor: require('../Images/sponsors/img-sponsor-native base.png'),
  paypalSponsor: require('../Images/sponsors/img-sponsor-paypal.png'),
  qlikSponsor: require('../Images/sponsors/img-sponsor-qlik-coffee.png'),
  rangleSponsor: require('../Images/sponsors/img-sponsor-rangle.io.png'),
  trainingSponsor: require('../Images/sponsors/img-sponsor-react native training.png'),
  salesforceSponsor: require('../Images/sponsors/img-sponsor-salesforce.png'),
  squarespaceSponsor: require('../Images/sponsors/img-sponsor-squarespace.png'),
  // app stuff
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  activeInfoIcon: require('../Images/Icons/icon-info-active.png'),
  inactiveInfoIcon: require('../Images/Icons/icon-info-inactive.png'),
  activeLocationIcon: require('../Images/Icons/icon-location-active.png'),
  inactiveLocationIcon: require('../Images/Icons/icon-location-inactive.png'),
  activeScheduleIcon: require('../Images/Icons/icon-schedule-active.png'),
  inactiveScheduleIcon: require('../Images/Icons/icon-schedule-inactive.png'),
  activeNotificationIcon: require('../Images/Icons/icon-notification-active.png'),
  inactiveNotificationIcon: require('../Images/Icons/icon-notification-inactive.png'),
  twitterIcon: require('../Images/Icons/icon-twitter-red.png'),
  githubIcon: require('../Images/Icons/icon-github-red.png'),
  arrowIcon: require('../Images/Icons/icon-arrow.png'),
  purpleArrowIcon: require('../Images/Icons/icon-purple-arrow.png'),
  markerIcon: require('../Images/Icons/icon-marker.png'),
  directionsIcon: require('../Images/Icons/icon-directions.png'),
  chevronIcon: require('../Images/Icons/icon-chevron.png'),
  coffeeBreak: require('../Images/bg-coffee-break.jpg'),
  lunchBreak: require('../Images/bg-lunch-break.jpg'),
  lunch: require('../Images/bg-lunch.png'),
  sponsor: require('../Images/sponsor.png'),
  theArmory: require('../Images/the-armory.png'),
  gradArmory: require('../Images/grad_armory.png'),
  slack: require('../Images/Icons/icon-slack.png'),
  blowhorn: require('../Images/Icons/icon-blowhorn.png'),
  squarespace: require('../Images/squarespace.png'),
  uberButton: require('../Images/uber-button.png'),
  lyftButton: require('../Images/lyft-button.png'),
  phase1: require('../Images/Icons/sun-phases/phase1.png'),
  phase2: require('../Images/Icons/sun-phases/phase2.png'),
  phase3: require('../Images/Icons/sun-phases/phase3.png'),
  phase4: require('../Images/Icons/sun-phases/phase4.png'),
  phase5: require('../Images/Icons/sun-phases/phase5.png'),
  phase6: require('../Images/Icons/sun-phases/phase6.png'),
  phase7: require('../Images/Icons/sun-phases/phase7.png'),
  phase8: require('../Images/Icons/sun-phases/phase8.png'),
  phase9: require('../Images/Icons/sun-phases/phase9.png'),
  phase10: require('../Images/Icons/sun-phases/phase10.png'),
  phase11: require('../Images/Icons/sun-phases/phase11.png'),
  phase12: require('../Images/Icons/sun-phases/phase12.png'),
  phase13: require('../Images/Icons/sun-phases/phase13.png'),
  phase14: require('../Images/Icons/sun-phases/phase14.png'),
  phase15: require('../Images/Icons/sun-phases/phase15.png'),
  phase16: require('../Images/Icons/sun-phases/phase16.png'),
  phase17: require('../Images/Icons/sun-phases/phase17.png'),
  phase18: require('../Images/Icons/sun-phases/phase18.png'),
  phase19: require('../Images/Icons/sun-phases/phase19.png'),
  phase20: require('../Images/Icons/sun-phases/phase20.png'),
  phase21: require('../Images/Icons/sun-phases/phase21.png'),
  phase22: require('../Images/Icons/sun-phases/phase22.png'),
  deschutesBrewery: require('../Images/deschutes-brewery.jpg'),
  littleBigBurger: require('../Images/little-big-burger.jpg'),
  tastyNAlder: require('../Images/tasty-n-alder.jpg'),
  fatHeadBrewery: require('../Images/fat-head-brewery.jpg')
}

export default images
