// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  activeInfoIcon: require('../Images/Icons/icon-info-active.png'),
  inactiveInfoIcon: require('../Images/Icons/icon-info-inactive.png'),
  activeLocationIcon: require('../Images/Icons/icon-location-active.png'),
  inactiveLocationIcon: require('../Images/Icons/icon-location-inactive.png'),
  activeScheduleIcon: require('../Images/Icons/icon-schedule-active.png'),
  inactiveScheduleIcon: require('../Images/Icons/icon-schedule-inactive.png'),
  activeNotificationIcon: require('../Images/Icons/icon-notification-active.png'),
  inactiveNotificationIcon: require('../Images/Icons/icon-notification-inactive.png'),
  twitterIcon: require('../Images/Icons/icon-twitter-red.png'),
  githubIcon: require('../Images/Icons/icon-github-red.png'),
  arrowIcon: require('../Images/Icons/icon-arrow.png'),
  sunIcon: require('../Images/Icons/icon-sun.png'),
  coffeeBreak: require('../Images/bg-coffee-break.png'),
  lunchBreak: require('../Images/bg-lunch-break.png'),
  lunch: require('../Images/bg-lunch.png'),
  sponsor: require('../Images/sponsor.png'),
  theArmory: require('../Images/the-armory.png')
}

export default images
