# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChainReactApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ChainReactApp
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # # You don't necessarily need all of these subspecs, but this would be a typical setup.
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge'
  ]

  target 'ChainReactAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ChainReactApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChainReactApp-tvOS

  target 'ChainReactApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
